### ISSUE TITLE
 rust-src component isn't mirrored

### ISSUE THREAD

**Issue by mikeymikeymikeymikey** [jiegec/rustup-mirror#8]
When running `rustup-mirror`, the `rust-src` package, which has a different naming format than the rest of the components, isn't downloaded.

Unlike the rest of the packages, there is just a single `rust-src-*.tar.xz` file for all targets, where it only differs between different toolchains (`rust-src-nightly.tar.xz`, `rust-src-1.50-tar.xz`).

**Comment by jiegec** [comment]
oh, I see..

**Comment by mikeymikeymikeymikey** [comment]
Sorry I wasn't clear, I meant the package isn't downloaded when `rustup-mirror` first starts.

**Comment by jiegec** [comment]
The package appears late in the toml, so it will be downloaded after other packages.

**Comment by mikeymikeymikeymikey** [comment]
I appears this was caused by code I added to filter downloads to only targets I use.
Sorry for the trouble.
